class Meatcan < Formula
  desc "macOS CAN terminal for MeatPi Ollie v2 GS USB firmware"
  homepage "https://github.com/42kko/MeatPI_CAN_MACOS"
  # Stable url/version/sha256 are generated by scripts/update_formula.py.
  head "https://github.com/42kko/MeatPI_CAN_MACOS.git", branch: "main"

  depends_on :macos
  depends_on "cmake" => :build
  depends_on "libusb"

  def install
    system "cmake", "-S", ".", "-B", "build", *std_cmake_args
    system "cmake", "--build", "build"
    system "ctest", "--test-dir", "build", "--output-on-failure"
    system "cmake", "--install", "build"
  end

  test do
    assert_match "meatcan", shell_output("#{bin}/meatcan --version")
    assert_match "send", shell_output("#{bin}/meatcan --help")
  end
end
