#!/usr/bin/env python3
"""Fetch a published immutable version tag and update Homebrew stable metadata."""
import argparse
import hashlib
from pathlib import Path
import re
import urllib.request

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('version', help='Version without v, e.g. 0.1.0')
args = parser.parse_args()
if not re.fullmatch(r'[0-9]+\.[0-9]+\.[0-9]+', args.version):
    parser.error('version must have the form MAJOR.MINOR.PATCH')
root = Path(__file__).resolve().parents[1]
url = f'https://github.com/42kko/MeatPI_CAN_MACOS/archive/refs/tags/v{args.version}.tar.gz'
# Download must succeed before any local file is changed. Tags must not be moved.
with urllib.request.urlopen(url, timeout=60) as response:
    archive = response.read()
if not archive.startswith(b'\x1f\x8b'):
    raise SystemExit('Release URL did not return a gzip source archive')
sha = hashlib.sha256(archive).hexdigest()
formula = root / 'Formula/meatcan.rb'
text = formula.read_text()
start = '  # BEGIN STABLE RELEASE\n'
end = '  # END STABLE RELEASE\n'
block = (start + f'  url "{url}"\n  version "{args.version}"\n'
         + f'  sha256 "{sha}"\n' + end)
if start in text:
    if end not in text:
        raise SystemExit('Malformed stable release block')
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    text = before + block + after
else:
    anchor = '  # Stable url/version/sha256 are generated by scripts/update_formula.py.\n'
    if anchor not in text:
        raise SystemExit('Formula release anchor is missing')
    text = text.replace(anchor, anchor + block, 1)
formula.write_text(text)
print(f'Updated {formula.relative_to(root)} to {args.version}')
print(f'SHA-256: {sha}')
print('Review and test the Formula, then commit and push it to main.')
